//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/friend.proto
namespace protos.friend
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendsList")]
  public partial class FriendsList : global::ProtoBuf.IExtensible
  {
    public FriendsList() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<FriendsList.PlayerModel> _playerList = new global::System.Collections.Generic.List<FriendsList.PlayerModel>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendsList.PlayerModel> playerList
    {
      get { return _playerList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerModel")]
  public partial class PlayerModel : global::ProtoBuf.IExtensible
  {
    public PlayerModel() {}
    
    private int _playerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _playerName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private string _headStr = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headStr
    {
      get { return _headStr; }
      set { _headStr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TradeWithFriend")]
  public partial class TradeWithFriend : global::ProtoBuf.IExtensible
  {
    public TradeWithFriend() {}
    
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _friendId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friendId
    {
      get { return _friendId; }
      set { _friendId = value; }
    }
    private int _userGold = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userGold
    {
      get { return _userGold; }
      set { _userGold = value; }
    }
    private int _friendGold = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"friendGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friendGold
    {
      get { return _friendGold; }
      set { _friendGold = value; }
    }
    private string _userWeapon = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"userWeapon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userWeapon
    {
      get { return _userWeapon; }
      set { _userWeapon = value; }
    }
    private string _friendWeapon = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"friendWeapon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string friendWeapon
    {
      get { return _friendWeapon; }
      set { _friendWeapon = value; }
    }
    private bool _isReady = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isReady", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isReady
    {
      get { return _isReady; }
      set { _isReady = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}