//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/ReturnMessage.proto
namespace protos.ReturnMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResDefaultInfo")]
  public partial class ResDefaultInfo : global::ProtoBuf.IExtensible
  {
    public ResDefaultInfo() {}
    
    private int _results = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int results
    {
      get { return _results; }
      set { _results = value; }
    }
    private string _details = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string details
    {
      get { return _details; }
      set { _details = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResCreateAccount")]
  public partial class ResCreateAccount : global::ProtoBuf.IExtensible
  {
    public ResCreateAccount() {}
    
    private int _resuts = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"resuts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resuts
    {
      get { return _resuts; }
      set { _resuts = value; }
    }
    private string _details = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string details
    {
      get { return _details; }
      set { _details = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResLogin")]
  public partial class ResLogin : global::ProtoBuf.IExtensible
  {
    public ResLogin() {}
    
    private int _results = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int results
    {
      get { return _results; }
      set { _results = value; }
    }
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _user_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private string _role = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string role
    {
      get { return _role; }
      set { _role = value; }
    }
    private int _endurance = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"endurance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endurance
    {
      get { return _endurance; }
      set { _endurance = value; }
    }
    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _user_level = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"user_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_level
    {
      get { return _user_level; }
      set { _user_level = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _vip_level = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private string _user_head_str = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"user_head_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_head_str
    {
      get { return _user_head_str; }
      set { _user_head_str = value; }
    }
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _mp = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private int _def = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _ad = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"ad", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ad
    {
      get { return _ad; }
      set { _ad = value; }
    }
    private int _sp = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"sp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sp
    {
      get { return _sp; }
      set { _sp = value; }
    }
    private int _dex = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"dex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dex
    {
      get { return _dex; }
      set { _dex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResGetRole")]
  public partial class ResGetRole : global::ProtoBuf.IExtensible
  {
    public ResGetRole() {}
    
    private int _results = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int results
    {
      get { return _results; }
      set { _results = value; }
    }
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _user_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private string _role = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string role
    {
      get { return _role; }
      set { _role = value; }
    }
    private int _endurance = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"endurance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endurance
    {
      get { return _endurance; }
      set { _endurance = value; }
    }
    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _user_level = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"user_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_level
    {
      get { return _user_level; }
      set { _user_level = value; }
    }
    private int _vip_level = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSysMessage")]
  public partial class ResSysMessage : global::ProtoBuf.IExtensible
  {
    public ResSysMessage() {}
    
    private int _results = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int results
    {
      get { return _results; }
      set { _results = value; }
    }
    private readonly global::System.Collections.Generic.List<ResSysMessage.MessageModel> _messageList = new global::System.Collections.Generic.List<ResSysMessage.MessageModel>();
    [global::ProtoBuf.ProtoMember(2, Name=@"messageList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResSysMessage.MessageModel> messageList
    {
      get { return _messageList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageModel")]
  public partial class MessageModel : global::ProtoBuf.IExtensible
  {
    public MessageModel() {}
    
    private string _type = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private int _fromId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fromId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fromId
    {
      get { return _fromId; }
      set { _fromId = value; }
    }
    private int _toId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"toId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int toId
    {
      get { return _toId; }
      set { _toId = value; }
    }
    private string _sendTime = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sendTime
    {
      get { return _sendTime; }
      set { _sendTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}